### ISSUE TITLE
jsnice.org is down

### ISSUE THREAD

**Issue by brettlangdon** [brettlangdon/jsnice#1]
It appears as though http://jsnice.org isn't running anymore, so this module isn't going to work anymore, unless it comes back.

**Comment by brettlangdon** [comment]
seems to be back up :D

**Comment by dy** [comment]
I'm seeing proxy error. Will this be available?

**Comment by brettlangdon** [comment]
hey @dy unfortunately I have no affiliation with jsnice.org so I won't be able to assist :(
