### ISSUE TITLE
there's error

### ISSUE THREAD

**Issue by axcsds** [brettlangdon/jsnice#12]
// Error compiling input. Try to check 'Transpile to ES5' in settings:

Line 1: Parse error. '(' expected

note: also not work with es5

**Comment by axcsds** [comment]
HELP

**Comment by axcsds** [comment]
PLS

**Comment by axcsds** [comment]
UPDATE!!!!

**Comment by axcsds** [comment]
NOW

**Comment by brettlangdon** [comment]
@axcsds I am sorry that you are having issues. However this client is just a dump http client for jsnice.org. I am in no way associated with jsnice.org. If there is an issue with how the code is parsed please reach out to jsnice.org
