### ISSUE TITLE
it does not take full path 

### ISSUE THREAD

**Issue by goromlagche** [brettlangdon/jsnice#2]
This particular line raises a bug incase I pass full path of my js file to the `jsnice` command https://github.com/brettlangdon/jsnice/blob/master/bin/jsnice#L27

**Comment by brettlangdon** [comment]
@goromlagche please update to version `0.1.1` which I just published. Should be resolved, let me know if it isn't.

**Comment by goromlagche** [comment]
thanks @brettlangdon  :+1:
