### ISSUE TITLE
language_in argument

### ISSUE THREAD

**Issue by MrHen** [brettlangdon/jsnice#5]
I received this output after attempting to process a rather large js file:

```
Error compiling input:

Line 175: Parse error. getters are not supported in older versions of JavaScript. If you are targeting newer versions of JavaScript, set the appropriate language_in option.
Line 193: Parse error. getters are not supported in older versions of JavaScript. If you are targeting newer versions of JavaScript, set the appropriate language_in option.
Line 193: Parse error. setters are not supported in older versions of JavaScript. If you are targeting newer versions of JavaScript, set the appropriate language_in option.
```

Looks like there is a `language_in` option but I don't see it documented anywhere. Any chance you can add this?

**Comment by brettlangdon** [comment]
@MrHen, yeah, I can't seem to find any documentation for it either, and I couldn't seem to figure out how `language_in=` would work either.

If you can get the `curl` to work with the appropriate `language_in=` parameter, then I am more than willing to add to this library, but unfortunately without a working example it probably wouldn't be very helpful.

Here is the curl command you can use (with the `language_in` value missing):

```
curl 'http://jsnice.org/beautify?pretty=1&rename=1&types=1&suggest=0&language_in=' --data $'function test(){ return 'test'; }'
```

I tried with ES6 generators, and it kept giving a syntax error no matter what I tried. I tried a few things that I assumed could make sense, like `es6`, `es2015`, `javascript`, etc.

However, it seems like `jsnice.org` doesn't support ES6.

**Comment by MrHen** [comment]
It seems like the error message is extremely similar to the errors generated by the [Closure Compiler](https://developers.google.com/closure/compiler/docs/api-tutorial1#how-to-communciate-with-the-api). I am still poking at it but I have a feeling the JS Nice API isn't actually exposing this flag.

**Comment by MrHen** [comment]
I contacted JS Nice directly and they do not expose compiler flags on the API.

**Comment by john-peterson** [comment]
put a huge banner on top of the readme

**BROKEN stuck on versions 3 go here instead**

- github.com/working/deobfuscater/best
- ... less good but working 
- worse but at least can be fixed

```
echo "var obj = { a: 1, b: 2, };">comma.js

google-closure-compiler --formatting PRETTY_PRINT --language_in ECMASCRIPT3 --js comma.js
stdin:1:22: ERROR - [JSC_TRAILING_COMMA] Parse error. IE8 (and below) will parse trailing commas in a

google-closure-compiler --formatting PRETTY_PRINT --language_in ECMASCRIPT5 --js comma.js
var obj = {a:1, b:2};

curl 'http://jsnice.org/beautify?pretty=1&rename=1&types=1&suggest=0&language_in=ECMASCRIPT5' --data "$(cat comma.js)"
{"js":"Error compiling input:\n\nLine 1: Parse error. IE8 (and below) will parse trailing commas in array and o

```

my one line unreadable script that still contains a gigantic hash after pretty print 

```
url=https://linux.die.net/man/2/getuid
agent="Mozilla/5.0 (X11; Linux x86_64; rv:30.0) Gecko/20100101 Firefox/30.0"

links -source -http.fake-user-agent "$agent" $url>getuid.links.html
xml_grep --html --text_only 'script' getuid.links.html>getuid.links.js
jsnice getuid.links.js

wc getuid.links.js
   1   83 6399 getuid.links.js

google-closure-compiler --formatting PRETTY_PRINT --language_in ECMASCRIPT5 --js getuid.links.js|wc
     19      98    6440

curl 'http://jsnice.org/beautify?pretty=1&rename=1&types=1&suggest=0&language_in=ECMASCRIPT5' --data "$(cat getuid.links.js)"
{"js":"Error compiling input:\n\nLine 1: Parse error. IE8 (and below) will parse trailing commas in array and object lite
```
